"""
Prompt engineering module for the Botanical AI assistant.

This module creates structured prompts that ground future AI
responses in the verified botanical knowledge base.
"""


class BotanicalPromptBuilder:
    """
    Builds safe and structured prompts for botanical responses.

    The prompt design separates:
    - system instructions
    - botanical context
    - user question
    - response requirements
    """

    SYSTEM_INSTRUCTION = """
You are a Botanical Intelligence Assistant for a biodiversity
field application.

Your role is to provide clear, educational, and evidence-grounded
information about plants.

IMPORTANT RULES:

1. Use the supplied botanical context as the primary source.
2. Do not invent plant characteristics, habitats, threats,
   conservation status, or ecological roles.
3. If the supplied context does not contain enough information
   to answer a question, clearly state that the information is
   not available in the current knowledge base.
4. Keep the response understandable to students, field users,
   and general audiences.
5. Preserve scientific names accurately.
6. Distinguish factual information from interpretation.
7. Prefer concise structured explanations over unsupported claims.
""".strip()

    RESPONSE_INSTRUCTIONS = """
Response requirements:

- Directly answer the user's question.
- Use the plant context provided below.
- Include the plant's common name when appropriate.
- Include the scientific name when relevant.
- Use bullet points for lists.
- Do not introduce facts that are absent from the context.
- If information is unavailable, say so explicitly.
""".strip()

    def build_prompt(
        self,
        plant_context,
        question,
        question_type="general"
    ):
        """
        Build a complete grounded prompt.

        Parameters:
            plant_context:
                Verified plant information generated by retrieval.py.

            question:
                User's botanical question.

            question_type:
                Classified question category such as botanical,
                ecology, conservation, facts, or general.

        Returns:
            A complete prompt string.
        """

        if not plant_context:
            raise ValueError(
                "Plant context cannot be empty."
            )

        if not question:
            raise ValueError(
                "Question cannot be empty."
            )

        prompt = f"""
{self.SYSTEM_INSTRUCTION}

----------------------------------------
BOTANICAL KNOWLEDGE CONTEXT
----------------------------------------

{plant_context}

----------------------------------------
USER QUESTION
----------------------------------------

{question}

----------------------------------------
QUESTION CATEGORY
----------------------------------------

{question_type}

----------------------------------------
RESPONSE INSTRUCTIONS
----------------------------------------

{self.RESPONSE_INSTRUCTIONS}

Generate the answer using the botanical context above.
""".strip()

        return prompt

    def build_conservation_prompt(
        self,
        plant_context,
        question
    ):
        """
        Build a conservation-focused prompt.
        """

        conservation_instruction = """
Focus specifically on conservation.

When relevant, organize the answer into:

1. Conservation status
2. Potential threats
3. Conservation actions

Do not infer that a plant is endangered unless the supplied
context explicitly states this.
""".strip()

        return self.build_prompt(
            plant_context=plant_context,
            question=question,
            question_type="conservation"
        ) + "\n\n" + conservation_instruction

    def build_ecology_prompt(
        self,
        plant_context,
        question
    ):
        """
        Build an ecology-focused prompt.
        """

        ecology_instruction = """
Focus specifically on ecology and biodiversity.

When relevant, discuss:

1. Habitat
2. Ecological importance
3. Biodiversity role
4. Relationships with the surrounding environment

Only use relationships explicitly supported by the context.
""".strip()

        return self.build_prompt(
            plant_context=plant_context,
            question=question,
            question_type="ecology"
        ) + "\n\n" + ecology_instruction

    def build_botanical_prompt(
        self,
        plant_context,
        question
    ):
        """
        Build a botanical-information prompt.
        """

        botanical_instruction = """
Focus specifically on botanical identification and
plant characteristics.

When relevant, discuss:

1. Common name
2. Scientific name
3. Family
4. Description
5. Physical characteristics
""".strip()

        return self.build_prompt(
            plant_context=plant_context,
            question=question,
            question_type="botanical"
        ) + "\n\n" + botanical_instruction

    def build_facts_prompt(
        self,
        plant_context,
        question
    ):
        """
        Build a prompt for educational plant facts.
        """

        facts_instruction = """
Focus on the interesting facts explicitly included
in the botanical context.

Do not add outside facts simply because they are
commonly known.
""".strip()

        return self.build_prompt(
            plant_context=plant_context,
            question=question,
            question_type="facts"
        ) + "\n\n" + facts_instruction


if __name__ == "__main__":

    builder = BotanicalPromptBuilder()

    sample_context = """
PLANT PROFILE

Common Name:
Neem

Scientific Name:
Azadirachta indica

Family:
Meliaceae

Habitat:
Warm tropical and subtropical environments.

Biodiversity Role:
Neem contributes to local plant diversity.
""".strip()

    sample_question = (
        "Why is Neem important for biodiversity?"
    )

    prompt = builder.build_ecology_prompt(
        plant_context=sample_context,
        question=sample_question
    )

    print("========================================")
    print("       BOTANICAL PROMPT BUILDER")
    print("========================================")

    print("\nPrompt successfully generated.\n")

    print("----------------------------------------")
    print("PROMPT PREVIEW")
    print("----------------------------------------")

    print(prompt)

    print("\n========================================")
    print("       PROMPT BUILDER READY")
    print("========================================")